DROP TABLE IF EXISTS movies.movie;

CREATE TABLE movies.movie (
  movie_id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(1000) DEFAULT NULL,
  budget INT DEFAULT NULL,
  homepage VARCHAR(1000) DEFAULT NULL,
  overview VARCHAR(1000) DEFAULT NULL,
  popularity DECIMAL(12,6) DEFAULT NULL,
  release_date DATE DEFAULT NULL,
  revenue BIGINT(20) DEFAULT NULL,
  runtime INT DEFAULT NULL,
  movie_status VARCHAR(50) DEFAULT NULL,
  tagline VARCHAR(1000) DEFAULT NULL,
  vote_average DECIMAL(4,2) DEFAULT NULL,
  vote_count INT DEFAULT NULL,
  CONSTRAINT pk_movie PRIMARY KEY (movie_id)
);

INSERT INTO movies.movie (movie_id, title, budget, homepage, overview, popularity, release_date, revenue, runtime, movie_status, tagline, vote_average, vote_count)
VALUES
(5,'Four Rooms',4000000,'','It\'s Ted the Bellhop\'s first night on the job...and the hotel\'s very unusual guests are about to place him in some outrageous predicaments. It seems that this evening\'s room service is serving up one unbelievable happening after another.',22.876230,'1995-12-09',4300000,98,'Released','Twelve outrageous guests. Four scandalous requests. And one lone bellhop, in his first day on the job, who\'s in for the wildest New year\'s Eve of his life.',6.50,530),
(11,'Star Wars',11000000,'http://www.starwars.com/films/star-wars-episode-iv-a-new-hope','Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',126.393695,'1977-05-25',775398007,121,'Released','A long time ago in a galaxy far, far away...',8.10,6624),
(12,'Finding Nemo',94000000,'http://movies.disney.com/finding-nemo','Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist\'s office aquarium. It\'s up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.',85.688789,'2003-05-30',940335536,100,'Released','There are 3.7 trillion fish in the ocean, they\'re looking for one.',7.60,6122),
(13,'Forrest Gump',55000000,'','A man with a low IQ has accomplished great things in his life and been present during significant historic events - in each case, far exceeding what anyone imagined he could do. Yet, despite all the things he has attained, his one true love eludes him. \'Forrest Gump\' is the story of a man who rose above his challenges, and who proved that determination, courage, and love are more important than ability.',138.133331,'1994-07-06',677945399,142,'Released','The world will never be the same, once you\'ve seen it through the eyes of Forrest Gump.',8.20,7927),
(279,'Amadeus',18000000,'','The incredible story of genius musician Wolfgang Amadeus Mozart, told in flashback by his peer and secret rival Antonio Salieri – now confined to an insane asylum.',31.826750,'1984-10-26',51973029,160,'Released','...Everything you\'ve heard is true',7.80,1076),
(280,'Terminator 2: Judgment Day',100000000,'','Nearly 10 years have passed since Sarah Connor was targeted for termination by a cyborg from the future. Now her son, John, the future leader of the resistance, is the target for a newer, more deadly terminator. Once again, the resistance has managed to send a protector back to attempt to save John and his mother Sarah.',101.741550,'1991-07-01',520000000,137,'Released','It\'s nothing personal.',7.70,4185),
(284,'The Apartment',3000000,'','Bud Baxter is a minor clerk in a huge New York insurance company, until he discovers a quick way to climb the corporate ladder. He lends out his apartment to the executives as a place to take their mistresses. Although he often has to deal with the aftermath of their visits, one night he\'s left with a major problem to solve.',22.889294,'1960-06-15',25000000,125,'Released','Movie-wise, there has never been anything like it - laugh-wise, love-wise, or otherwise-wise!',8.10,483),
(285,'Pirates of the Caribbean: At World\'s End',300000000,'http://disney.go.com/disneypictures/pirates/','Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.',139.082615,'2007-05-19',961000000,169,'Released','At the end of the world, the adventure begins.',6.90,4500),
(559,'Spider-Man 3',258000000,'http://www.sonypictures.com/movies/spider-man3/','The seemingly invincible Spider-Man goes up against an all-new crop of villain – including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.',115.699814,'2007-05-01',890871626,139,'Released','The battle within.',5.90,3576),
(767,'Harry Potter and the Half-Blood Prince',250000000,'http://harrypotter.warnerbros.com/harrypotterandthehalf-bloodprince/dvd/index.html','As Harry begins his sixth year at Hogwarts, he discovers an old book marked as \'Property of the Half-Blood Prince\', and begins to learn more about Lord Voldemort\'s dark past.',98.885637,'2009-07-07',933959197,153,'Released','Dark Secrets Revealed',7.40,5293),
(1891,'The Empire Strikes Back',18000000,'http://www.starwars.com/films/star-wars-episode-v-the-empire-strikes-back','The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.',78.517830,'1980-05-17',538400000,124,'Released','The Adventure Continues...',8.20,5879),
(1892,'Return of the Jedi',32350000,'http://www.starwars.com/films/star-wars-episode-vi-return-of-the-jedi','As Rebel leaders map their strategy for an all-out attack on the Emperor\'s newer, bigger Death Star. Han Solo remains frozen in the cavernous desert fortress of Jabba the Hutt, the most loathsome outlaw in the universe, who is also keeping Princess Leia as a slave girl. Now a master of the Force, Luke Skywalker rescues his friends, but he cannot become a true Jedi Knight until he wages his own crucial battle against Darth Vader, who has sworn to win Luke over to the dark side of the Force.',46.509071,'1983-05-23',572700000,135,'Released','The Empire Falls...',7.90,4665),
(1893,'Star Wars: Episode I - The Phantom Menace',115000000,'http://www.starwars.com/films/star-wars-episode-i-the-phantom-menace','Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.',54.035265,'1999-05-19',924317558,136,'Released','Every generation has a legend. Every journey has a first step. Every saga has a beginning.',6.30,4432);